### ISSUE TITLE
ME Proxy crashes the game on 1.18.2

### ISSUE THREAD

**Issue by DomezTheDragon** [RuochenFu21/CreateAppliedKinetics#7]
just as the title says, try to put a item in or out and yeah
1.3.2 is the mod version

**Comment by furuochen-dev** [comment]
Video showcasing? How to reproduce?

**Comment by DomezTheDragon** [comment]
i contacted the developer myself directly, they are currently handling it

**Comment by furuochen-dev** [comment]
I am the developer.

**Comment by DomezTheDragon** [comment]
oh i am dumb lmfao, but yeah i already showed you how to reproduce
https://discord.com/channels/1034812032823861248/1034812033759203387/1228040342398304429

**Comment by mlus-asuka** [comment]
still exists
java.lang.NullPointerException: Cannot invoke "appeng.api.stacks.AEKey.getType()" because "what" is null
	at TRANSFORMER/ae2@15.2.11/appeng.me.storage.CompositeStorage.extract(CompositeStorage.java:56)
	at TRANSFORMER/ae2@15.2.11/appeng.me.storage.DelegatingMEInventory.extract(DelegatingMEInventory.java:46)
	at TRANSFORMER/ae2@15.2.11/appeng.me.storage.MEInventoryHandler.extract(MEInventoryHandler.java:95)
	at TRANSFORMER/ae2@15.2.11/appeng.me.storage.NetworkStorage.extract(NetworkStorage.java:225)
	at TRANSFORMER/createappliedkinetics@1.3.2-1.20.1/com.forsteri.createappliedkinetics.content.meProxy.MEProxyInventoryHandler.extractItem(MEProxyInventoryHandler.java:108)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.updateChecklist(SchematicannonBlockEntity.java:836)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.initializePrinter(SchematicannonBlockEntity.java:483)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tickPaperPrinter(SchematicannonBlockEntity.java:684)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tick(SchematicannonBlockEntity.java:278)
	at TRANSFORMER/create@0.5.1.f/com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$7(LevelChunk.java)
	at TRANSFORMER/neruina@2.0.0-beta.10/com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:168)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$zmh000$catchTickingBlockEntity$notTheCauseOfTickLag(LevelChunk.java:815)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.redirect$bjk000$observable$redirectTick(Level.java:2040)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46463_(Level.java:468)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Cuttleguy** [comment]
> still exists java.lang.NullPointerException: Cannot invoke "appeng.api.stacks.AEKey.getType()" because "what" is null at TRANSFORMER/ae2@15.2.11/appeng.me.storage.CompositeStorage.extract(CompositeStorage.java:56) at TRANSFORMER/ae2@15.2.11/appeng.me.storage.DelegatingMEInventory.extract(DelegatingMEInventory.java:46) at TRANSFORMER/ae2@15.2.11/appeng.me.storage.MEInventoryHandler.extract(MEInventoryHandler.java:95) at TRANSFORMER/ae2@15.2.11/appeng.me.storage.NetworkStorage.extract(NetworkStorage.java:225) at TRANSFORMER/createappliedkinetics@1.3.2-1.20.1/com.forsteri.createappliedkinetics.content.meProxy.MEProxyInventoryHandler.extractItem(MEProxyInventoryHandler.java:108) at TRANSFORMER/[create@0.5.1.f](mailto:create@0.5.1.f)/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.updateChecklist(SchematicannonBlockEntity.java:836) at TRANSFORMER/[create@0.5.1.f](mailto:create@0.5.1.f)/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.initializePrinter(SchematicannonBlockEntity.java:483) at TRANSFORMER/[create@0.5.1.f](mailto:create@0.5.1.f)/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tickPaperPrinter(SchematicannonBlockEntity.java:684) at TRANSFORMER/[create@0.5.1.f](mailto:create@0.5.1.f)/com.simibubi.create.content.schematics.cannon.SchematicannonBlockEntity.tick(SchematicannonBlockEntity.java:278) at TRANSFORMER/[create@0.5.1.f](mailto:create@0.5.1.f)/com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$7(LevelChunk.java) at TRANSFORMER/neruina@2.0.0-beta.10/com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:168) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$zmh000$catchTickingBlockEntity$notTheCauseOfTickLag(LevelChunk.java:815) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.redirect$bjk000$observable$redirectTick(Level.java:2040) at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46463_(Level.java:468) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) at java.base/java.lang.Thread.run(Thread.java:840)

Can confirm, 1.19.2 as well

**Comment by hooded-person** [comment]
also on 1.20.1

**Comment by DomezTheDragon** [comment]
> also on 1.20.1

damn, so i wonder if it's ever going to get a fix

**Comment by allanf181** [comment]
https://github.com/RuochenFu21/CreateAppliedKinetics/blob/9455cc99ac3a0843084a1a0fe03c0e103b364375/src/main/java/com/forsteri/createappliedkinetics/content/meProxy/MEProxyInventoryHandler.java#L108
AEItemKey is null, this needs to be validated before calling extract
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/92e8deec2417040a46274f3789e97abff485585e/src/main/java/appeng/api/stacks/AEItemKey.java#L65-L72


https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/92e8deec2417040a46274f3789e97abff485585e/src/main/java/appeng/helpers/externalstorage/GenericStackItemStorage.java#L54-L63

**Comment by SuckItVanBuren** [comment]
Just wanted to add that I am also having the same issue and I'm on 1.19.2

I'll also add that I noticed that at one point it was crashing _specifically_ because my ME storage drives were full and new items could not be deposited by the proxies. I think now, however, the issue is just the sheer number of proxies we have now (we way over compensated on storage). I can provide further documentation if necessary. 

It's quite debilitating gameplay-wise and makes my server almost unplayable. I'm afraid it would also take too long to remove the proxies before it crashes again, so I'm willing to do as much as possible to assist you in fixing this.

**Comment by hooded-person** [comment]
If you are using the proxy's to put items into your system, you can use ME interfaces for inputs, you can also stock a certain amount of selected items which you could extract with filters

**Comment by furuochen-dev** [comment]
Will be fix on the next version (1.20.1/1.21)
